// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MsgCountPlusNET.json;
//
//    var jGuilds = JGuilds.FromJson(jsonString);

namespace MsgCountPlusNET.json
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class jGuilds
    {
        public static List<jGuild> FromJson(string json) => JsonConvert.DeserializeObject<List<jGuild>>(json, MsgCountPlusNET.json.jGuilds_Converter.Settings);
    }

    public static class jGuilds_Serialize
    {
        public static string ToJson(this List<jGuild> self) => JsonConvert.SerializeObject(self, MsgCountPlusNET.json.jGuilds_Converter.Settings);
    }

    internal static class jGuilds_Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
